### ISSUE TITLE
2DS Black Screen

### ISSUE THREAD

**Issue by lendsp** [MrHuu/openbor-3ds#3]
I'm trying to run on nintendo 2ds but the screen goes black.

If I press the home button I see the screen, but if I go back to OpenBOR it is black again.

I can even enter the games and listen to the audio, but the screen remains black

Does anyone know what I need to do?

**Comment by MrHuu** [comment]
On a 3ds or new2ds, the bottom screen backlight is disabled.
The (old) 2ds only has a single screen which gets disabled completely.

Right now i'm unable to provide a proper update, but in the meantime you could use this build: [openbor.zip](https://github.com/MrHuu/openbor-3ds/files/8501306/openbor.zip)
This build has the backlight toggle disabled.

**Comment by lendsp** [comment]
Thank you
